package com.cryptopulse.app.domain.validation

enum class ValidationErrorReason {
    EXCHANGE_METADATA_UNAVAILABLE,
    INVALID_INPUT_PARAMETERS,
    PRICE_BELOW_MINIMUM,
    PRICE_ABOVE_MAXIMUM,
    INVALID_TICK_SIZE,
    MIN_QTY_FAILED,
    MAX_QTY_FAILED,
    INVALID_STEP_SIZE,
    MIN_NOTIONAL_FAILED,
    MAX_POSITION_FAILED,
    EXCHANGE_RULES_UPDATED,
    PRICE_VARIANCE_EXCEEDED
}
