-- Migration 0016: Add Production Trading Engine & Native Protection Columns
ALTER TABLE trade_positions ADD COLUMN order_type TEXT DEFAULT 'LIMIT';
ALTER TABLE trade_positions ADD COLUMN limit_price REAL;
ALTER TABLE trade_positions ADD COLUMN entry_exchange_order_id TEXT;
ALTER TABLE trade_positions ADD COLUMN tp_exchange_order_id TEXT;
ALTER TABLE trade_positions ADD COLUMN sl_exchange_order_id TEXT;
ALTER TABLE trade_positions ADD COLUMN oco_group_id TEXT;
ALTER TABLE trade_positions ADD COLUMN protection_mode TEXT DEFAULT 'NATIVE_OCO';
ALTER TABLE trade_positions ADD COLUMN entry_status TEXT DEFAULT 'PENDING';
ALTER TABLE trade_positions ADD COLUMN tp_status TEXT;
ALTER TABLE trade_positions ADD COLUMN sl_status TEXT;
ALTER TABLE trade_positions ADD COLUMN filled_quantity REAL DEFAULT 0;
ALTER TABLE trade_positions ADD COLUMN average_fill_price REAL;
ALTER TABLE trade_positions ADD COLUMN execution_source TEXT DEFAULT 'EXCHANGE';
ALTER TABLE trade_positions ADD COLUMN entry_submitted_at TEXT;
ALTER TABLE trade_positions ADD COLUMN entry_accepted_at TEXT;
ALTER TABLE trade_positions ADD COLUMN entry_filled_at TEXT;
ALTER TABLE trade_positions ADD COLUMN tp_submitted_at TEXT;
ALTER TABLE trade_positions ADD COLUMN tp_filled_at TEXT;
ALTER TABLE trade_positions ADD COLUMN sl_submitted_at TEXT;
ALTER TABLE trade_positions ADD COLUMN sl_filled_at TEXT;
ALTER TABLE trade_positions ADD COLUMN exit_submitted_at TEXT;
ALTER TABLE trade_positions ADD COLUMN exit_filled_at TEXT;
ALTER TABLE trade_positions ADD COLUMN exit_exchange_order_id TEXT;
ALTER TABLE trade_positions ADD COLUMN exchange_execution_latency_ms INTEGER;
ALTER TABLE trade_positions ADD COLUMN last_health_check_at TEXT;
ALTER TABLE trade_positions ADD COLUMN retry_count INTEGER DEFAULT 0;
ALTER TABLE trade_positions ADD COLUMN last_retry_reason TEXT;
ALTER TABLE trade_positions ADD COLUMN last_event_time INTEGER DEFAULT 0;
ALTER TABLE trade_positions ADD COLUMN ws_stream_status TEXT DEFAULT 'DISCONNECTED';
